language: node_js
node_js:
  - "7.7.4"
install: 
  - npm install
script:
  - npm test
cache:
  directories:
   - "node_modules"
before_script:
  - psql -c 'create database event_manager;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - npm run coveralls
