language: node_js
node_js:
  - "7.7.4"
install: 
  - npm install
  - npm install codecov -g
  - npm install nyc coveralls
script:
  - npm run migrate
  - npm run seed
  - npm test
before_script:
  - psql -c 'create database event_manager;' -U postgres
  
after_success:
  - npm run coveralls
